# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get a parameter known g and b
#' 
#' \code{g2a} returns the a parameter known g and b
#' 
#' @param g the g parameter
#' @param b the b parameter
#' 
#' @return a real value
#' 
#' @examples
#' 
#' g2a(10,2)
#' 
#' @export
g2a <- function(g, b) {
    .Call('mbbefd_g2a', PACKAGE = 'mbbefd', g, b)
}

dmbbefdC <- function(x, a, b) {
    .Call('mbbefd_dmbbefdC', PACKAGE = 'mbbefd', x, a, b)
}

f4Sampler <- function(x, a, b) {
    .Call('mbbefd_f4Sampler', PACKAGE = 'mbbefd', x, a, b)
}

