# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' inverse CDF function
#' 
#' \code{f4Sampler} returns the x known the probability level x and distribution parameters a and b
#' 
#' @param x: the probability
#' @param a: parameter of the mbbefd density function
#' @param b: parameter of the mbbefd density function
#' 
#' @return a real value
#' 
#' @example
#' 
#' f4Sampler(x=.2, a=.2, b=.05)
NULL

#' random number generation - 1st param
#' 
#' \code{rmbbefdC2} generates random variates distribution parameters a and b
#' 
#' @param n: the number of random variates
#' @param a: first shape parameter
#' @param b: second shape parameter
#' 
#' @return a vector of real values
#' 
#' @example
#' 
#' rmbbefdC2(n=10, a=.2, b=.05)
NULL

#' Get a parameter known g and b
#' 
#' \code{g2a} returns the a parameter known g and b
#' 
#' @param g the g parameter
#' @param b the b parameter
#' 
#' @return a real value
#' 
#' @examples
#' 
#' g2a(10,2)
#' 
#' @export
g2a <- function(g, b) {
    .Call('mbbefd_g2a', PACKAGE = 'mbbefd', g, b)
}

.dmbbefdC <- function(x, a, b) {
    .Call('mbbefd_dmbbefdC', PACKAGE = 'mbbefd', x, a, b)
}

.f4Sampler <- function(x, a, b) {
    .Call('mbbefd_f4Sampler', PACKAGE = 'mbbefd', x, a, b)
}

.rmbbefdC2 <- function(n, a, b) {
    .Call('mbbefd_rmbbefdC2', PACKAGE = 'mbbefd', n, a, b)
}

